[phases.setup]
nixPkgs = ["php82", "curl"]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "chmod +x /usr/local/bin/composer",
    "/usr/local/bin/composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
    "echo 'Build completed successfully'"
]

[start]
cmd = "cd /app/public && php -S 0.0.0.0:$PORT router.php"