[phases.setup]
nixPkgs = ["php82", "curl", "nginx"]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "chmod +x /usr/local/bin/composer",
    "/usr/local/bin/composer install --no-dev --optimize-autoloader",
    "mkdir -p /run/php-fpm",
    "chmod +x /app/start.sh"
]

[phases.build]
cmds = [
    "echo 'Build completed'"
]

[start]
cmd = "/app/start.sh"