[phases.setup]
nixPkgs = ["php82", "composer", "nginx"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
    "echo 'Build completed'"
]

[start]
cmd = "php spark serve --host=0.0.0.0 --port=$PORT"
